frase = ' Camelo voador '
print(frase[8])
print(len(frase))
print(frase.count('o',0,14))
print(frase.find('melo'))
print('melo' in frase)
print(frase.replace('voador','Mamador'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.split())
print('-'.join(frase))